package Sample

import com.techgap.DroolsAverage.DroolsAverage.EmployeeClass.Employee;

rule "Test"
	when
	then
		System.out.println("here");
end
rule "Test Rule"

    when
        e : Employee( calculate == 0, 
        			  kpi1 : performance1,
        			  kpi2 : performance2,
        			  kpi3 : performance3,
        			  kpi4 : performance4)
    then
    	java.math.BigDecimal result1 = kpi1.add(kpi2);
    	java.math.BigDecimal result2 = result1.add(kpi3);
    	java.math.BigDecimal result3 = result2.add(kpi4);
    	
        e.setPerformanceTotal(result3);

end
