#created on: Oct 17, 2018
package Sample


import com.techgap.droolsaverage.model.EmployeeClass.Employee;


rule "Weekly Average"
    when
        e : Employee( calculate == 0, 
        				hours : weeklyHours,
        				days  : numDaysWorked)
    then
        #System.out.println("Hours worked => " + hours + "Number of days worked => " + days);
        e.setAverage(hours / days);
        #System.out.println("Average hours worked per day => " + e.getAverage());
        e.setPerformance1(e.getAverage());

end

rule "Rule Two"
    when
        e : Employee( calculate == 0 ,
        			  hours : weeklyHours,
        			  days  : numDaysWorked)
    then
        e.setPerformance2(days);

end
